export enum ErrorCode {
  // 400 Bad Request
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  TYPE_MISMATCH = 'TYPE_MISMATCH',
  MALFORMED_REQUEST = 'MALFORMED_REQUEST',
  FILE_UPLOAD_ERROR = 'FILE_UPLOAD_ERROR',

  // 401 Unauthorized
  AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',

  // 403 Forbidden
  ACCESS_DENIED = 'ACCESS_DENIED',

  // 404 Not Found
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',

  // 405 Method Not Allowed
  METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED',

  // 409 Conflict
  RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS',
  DATA_INTEGRITY_VIOLATION = 'DATA_INTEGRITY_VIOLATION',
  CONCURRENCY_CONFLICT = 'CONCURRENCY_CONFLICT',
  INVALID_STATE = 'INVALID_STATE',

  // 413 Payload Too Large
  FILE_SIZE_LIMIT_EXCEEDED = 'FILE_SIZE_LIMIT_EXCEEDED',

  // 422 Unprocessable Entity
  BUSINESS_RULE_VIOLATION = 'BUSINESS_RULE_VIOLATION',

  // 423 Locked
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',

  // 429 Too Many Requests
  LIMIT_EXCEEDED = 'LIMIT_EXCEEDED',

  // 500 & Infrastructure Errors
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',
  TIMEOUT = 'TIMEOUT',

  // Fallback Client Codes
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}

