spring:
  datasource:
    url: jdbc:postgresql://${vaops.databases.primary.host}:${vaops.databases.primary.port}/${vaops.databases.primary.name}?currentSchema=public
    username: ${vaops.databases.primary.username}
    password: ${vaops.databases.primary.password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20 # Maximum number of connections in the pool
      minimum-idle: 5 # Minimum number of idle connections to maintain
      connection-timeout: 30000 # Maximum time (ms) to wait for a connection from the pool
      idle-timeout: 600000 # Maximum time (ms) a connection is allowed to sit idle in the pool (10 minutes)
      max-lifetime: 1800000 # Maximum lifetime (ms) of a connection in the pool (30 minutes)
      pool-name: VaopsPrimaryHikariPool # Name of the connection pool for logs and monitoring
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true

logging:
  level:
    root: info
    c4f.vannang.vaops: debug

vaops:
  app:
    is-prod: false
  auth:
    jwt:
      access-expiration-ms: 20000
      refresh-expiration-ms: 50000

