spring:
  application:
    name: vaops
  profiles:
    active: dev
  threads:
    virtual:
      enabled: true

server:
  port: 8080
vaops:
  app:
    is-prod: false
  databases:
    primary:
      host: 127.0.0.1
      port: 5432
      name: vaops
      username: postgres
      password: postgres

  auth:
    jwt:
      access-secret: XAYszf4TlHIjVGNDWEaKKb1e6ven3vJF4CJBqid0545
      access-expiration-ms: 3600000
      refresh-secret: XAYszf4TlHIjVGNDWEaKKb1e6ven3vJF4CJBqid0545
      refresh-expiration-ms: 604800000

